/**
 * 🎨 SuperCode TUI Themes
 * Modern IDE-inspired themes with full customization
 */

export interface ThemeColors {
  // Primary colors
  primary: string;
  secondary: string;
  accent: string;
  
  // Background colors
  bg: string;
  bgAlt: string;
  bgHighlight: string;
  bgSelected: string;
  
  // Text colors
  text: string;
  textMuted: string;
  textHighlight: string;
  textInverse: string;
  
  // Status colors
  success: string;
  warning: string;
  error: string;
  info: string;
  
  // Border colors
  border: string;
  borderFocus: string;
  borderMuted: string;
  
  // Syntax highlighting
  keyword: string;
  string: string;
  number: string;
  comment: string;
  function: string;
  variable: string;
  operator: string;
  type: string;
}

export interface Theme {
  name: string;
  displayName: string;
  description: string;
  author: string;
  type: 'dark' | 'light';
  colors: ThemeColors;
  icons: {
    folder: string;
    file: string;
    agent: string;
    model: string;
    tool: string;
    function: string;
    memory: string;
    workflow: string;
    chat: string;
    settings: string;
    success: string;
    error: string;
    warning: string;
    info: string;
    running: string;
    stopped: string;
    loading: string;
  };
}

// VS Code Dark+ Theme
export const vscodeDark: Theme = {
  name: 'vscode-dark',
  displayName: 'VS Code Dark+',
  description: 'The classic VS Code dark theme',
  author: 'Microsoft',
  type: 'dark',
  colors: {
    primary: '#007ACC',
    secondary: '#3794FF',
    accent: '#0E639C',
    bg: '#1E1E1E',
    bgAlt: '#252526',
    bgHighlight: '#2D2D2D',
    bgSelected: '#094771',
    text: '#D4D4D4',
    textMuted: '#808080',
    textHighlight: '#FFFFFF',
    textInverse: '#1E1E1E',
    success: '#4EC9B0',
    warning: '#CCA700',
    error: '#F14C4C',
    info: '#3794FF',
    border: '#3C3C3C',
    borderFocus: '#007ACC',
    borderMuted: '#2D2D2D',
    keyword: '#569CD6',
    string: '#CE9178',
    number: '#B5CEA8',
    comment: '#6A9955',
    function: '#DCDCAA',
    variable: '#9CDCFE',
    operator: '#D4D4D4',
    type: '#4EC9B0',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Dracula Theme
export const dracula: Theme = {
  name: 'dracula',
  displayName: 'Dracula',
  description: 'A dark theme for vampires',
  author: 'Zeno Rocha',
  type: 'dark',
  colors: {
    primary: '#BD93F9',
    secondary: '#FF79C6',
    accent: '#8BE9FD',
    bg: '#282A36',
    bgAlt: '#21222C',
    bgHighlight: '#44475A',
    bgSelected: '#44475A',
    text: '#F8F8F2',
    textMuted: '#6272A4',
    textHighlight: '#FFFFFF',
    textInverse: '#282A36',
    success: '#50FA7B',
    warning: '#FFB86C',
    error: '#FF5555',
    info: '#8BE9FD',
    border: '#44475A',
    borderFocus: '#BD93F9',
    borderMuted: '#383A46',
    keyword: '#FF79C6',
    string: '#F1FA8C',
    number: '#BD93F9',
    comment: '#6272A4',
    function: '#50FA7B',
    variable: '#F8F8F2',
    operator: '#FF79C6',
    type: '#8BE9FD',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🦇',
    model: '🧛',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// One Dark Pro Theme
export const oneDarkPro: Theme = {
  name: 'one-dark-pro',
  displayName: 'One Dark Pro',
  description: 'Atom One Dark theme for VS Code',
  author: 'binaryify',
  type: 'dark',
  colors: {
    primary: '#61AFEF',
    secondary: '#C678DD',
    accent: '#98C379',
    bg: '#282C34',
    bgAlt: '#21252B',
    bgHighlight: '#2C313A',
    bgSelected: '#3E4451',
    text: '#ABB2BF',
    textMuted: '#5C6370',
    textHighlight: '#FFFFFF',
    textInverse: '#282C34',
    success: '#98C379',
    warning: '#E5C07B',
    error: '#E06C75',
    info: '#61AFEF',
    border: '#3E4451',
    borderFocus: '#61AFEF',
    borderMuted: '#2C313A',
    keyword: '#C678DD',
    string: '#98C379',
    number: '#D19A66',
    comment: '#5C6370',
    function: '#61AFEF',
    variable: '#E06C75',
    operator: '#56B6C2',
    type: '#E5C07B',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Nord Theme
export const nord: Theme = {
  name: 'nord',
  displayName: 'Nord',
  description: 'An arctic, north-bluish color palette',
  author: 'Arctic Ice Studio',
  type: 'dark',
  colors: {
    primary: '#88C0D0',
    secondary: '#81A1C1',
    accent: '#5E81AC',
    bg: '#2E3440',
    bgAlt: '#3B4252',
    bgHighlight: '#434C5E',
    bgSelected: '#4C566A',
    text: '#ECEFF4',
    textMuted: '#D8DEE9',
    textHighlight: '#FFFFFF',
    textInverse: '#2E3440',
    success: '#A3BE8C',
    warning: '#EBCB8B',
    error: '#BF616A',
    info: '#88C0D0',
    border: '#4C566A',
    borderFocus: '#88C0D0',
    borderMuted: '#3B4252',
    keyword: '#81A1C1',
    string: '#A3BE8C',
    number: '#B48EAD',
    comment: '#616E88',
    function: '#88C0D0',
    variable: '#D8DEE9',
    operator: '#81A1C1',
    type: '#8FBCBB',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Monokai Pro Theme
export const monokaiPro: Theme = {
  name: 'monokai-pro',
  displayName: 'Monokai Pro',
  description: 'Professional Monokai theme',
  author: 'Monokai',
  type: 'dark',
  colors: {
    primary: '#FFD866',
    secondary: '#FF6188',
    accent: '#78DCE8',
    bg: '#2D2A2E',
    bgAlt: '#221F22',
    bgHighlight: '#403E41',
    bgSelected: '#5B595C',
    text: '#FCFCFA',
    textMuted: '#939293',
    textHighlight: '#FFFFFF',
    textInverse: '#2D2A2E',
    success: '#A9DC76',
    warning: '#FFD866',
    error: '#FF6188',
    info: '#78DCE8',
    border: '#5B595C',
    borderFocus: '#FFD866',
    borderMuted: '#403E41',
    keyword: '#FF6188',
    string: '#FFD866',
    number: '#AB9DF2',
    comment: '#727072',
    function: '#A9DC76',
    variable: '#FCFCFA',
    operator: '#FF6188',
    type: '#78DCE8',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// GitHub Dark Theme
export const githubDark: Theme = {
  name: 'github-dark',
  displayName: 'GitHub Dark',
  description: 'GitHub official dark theme',
  author: 'GitHub',
  type: 'dark',
  colors: {
    primary: '#58A6FF',
    secondary: '#F78166',
    accent: '#7EE787',
    bg: '#0D1117',
    bgAlt: '#161B22',
    bgHighlight: '#21262D',
    bgSelected: '#30363D',
    text: '#C9D1D9',
    textMuted: '#8B949E',
    textHighlight: '#FFFFFF',
    textInverse: '#0D1117',
    success: '#7EE787',
    warning: '#D29922',
    error: '#F85149',
    info: '#58A6FF',
    border: '#30363D',
    borderFocus: '#58A6FF',
    borderMuted: '#21262D',
    keyword: '#FF7B72',
    string: '#A5D6FF',
    number: '#79C0FF',
    comment: '#8B949E',
    function: '#D2A8FF',
    variable: '#FFA657',
    operator: '#FF7B72',
    type: '#7EE787',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Catppuccin Mocha Theme
export const catppuccinMocha: Theme = {
  name: 'catppuccin-mocha',
  displayName: 'Catppuccin Mocha',
  description: 'Soothing pastel theme for the high-spirited',
  author: 'Catppuccin',
  type: 'dark',
  colors: {
    primary: '#CBA6F7',
    secondary: '#F5C2E7',
    accent: '#94E2D5',
    bg: '#1E1E2E',
    bgAlt: '#181825',
    bgHighlight: '#313244',
    bgSelected: '#45475A',
    text: '#CDD6F4',
    textMuted: '#A6ADC8',
    textHighlight: '#FFFFFF',
    textInverse: '#1E1E2E',
    success: '#A6E3A1',
    warning: '#F9E2AF',
    error: '#F38BA8',
    info: '#89DCEB',
    border: '#45475A',
    borderFocus: '#CBA6F7',
    borderMuted: '#313244',
    keyword: '#CBA6F7',
    string: '#A6E3A1',
    number: '#FAB387',
    comment: '#6C7086',
    function: '#89B4FA',
    variable: '#F5C2E7',
    operator: '#89DCEB',
    type: '#F9E2AF',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🐱',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Tokyo Night Theme
export const tokyoNight: Theme = {
  name: 'tokyo-night',
  displayName: 'Tokyo Night',
  description: 'A clean, dark theme that celebrates the lights of Tokyo at night',
  author: 'enkia',
  type: 'dark',
  colors: {
    primary: '#7AA2F7',
    secondary: '#BB9AF7',
    accent: '#7DCFFF',
    bg: '#1A1B26',
    bgAlt: '#16161E',
    bgHighlight: '#292E42',
    bgSelected: '#33467C',
    text: '#A9B1D6',
    textMuted: '#565F89',
    textHighlight: '#C0CAF5',
    textInverse: '#1A1B26',
    success: '#9ECE6A',
    warning: '#E0AF68',
    error: '#F7768E',
    info: '#7DCFFF',
    border: '#292E42',
    borderFocus: '#7AA2F7',
    borderMuted: '#1F2335',
    keyword: '#BB9AF7',
    string: '#9ECE6A',
    number: '#FF9E64',
    comment: '#565F89',
    function: '#7AA2F7',
    variable: '#C0CAF5',
    operator: '#89DDFF',
    type: '#2AC3DE',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Gruvbox Dark Theme
export const gruvboxDark: Theme = {
  name: 'gruvbox-dark',
  displayName: 'Gruvbox Dark',
  description: 'Retro groove color scheme',
  author: 'morhetz',
  type: 'dark',
  colors: {
    primary: '#FABD2F',
    secondary: '#B8BB26',
    accent: '#83A598',
    bg: '#282828',
    bgAlt: '#1D2021',
    bgHighlight: '#3C3836',
    bgSelected: '#504945',
    text: '#EBDBB2',
    textMuted: '#928374',
    textHighlight: '#FBF1C7',
    textInverse: '#282828',
    success: '#B8BB26',
    warning: '#FABD2F',
    error: '#FB4934',
    info: '#83A598',
    border: '#504945',
    borderFocus: '#FABD2F',
    borderMuted: '#3C3836',
    keyword: '#FB4934',
    string: '#B8BB26',
    number: '#D3869B',
    comment: '#928374',
    function: '#FABD2F',
    variable: '#83A598',
    operator: '#FE8019',
    type: '#8EC07C',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Solarized Dark Theme
export const solarizedDark: Theme = {
  name: 'solarized-dark',
  displayName: 'Solarized Dark',
  description: 'Precision colors for machines and people',
  author: 'Ethan Schoonover',
  type: 'dark',
  colors: {
    primary: '#268BD2',
    secondary: '#2AA198',
    accent: '#B58900',
    bg: '#002B36',
    bgAlt: '#073642',
    bgHighlight: '#094959',
    bgSelected: '#0A5A6E',
    text: '#839496',
    textMuted: '#657B83',
    textHighlight: '#FDF6E3',
    textInverse: '#002B36',
    success: '#859900',
    warning: '#B58900',
    error: '#DC322F',
    info: '#268BD2',
    border: '#094959',
    borderFocus: '#268BD2',
    borderMuted: '#073642',
    keyword: '#859900',
    string: '#2AA198',
    number: '#D33682',
    comment: '#586E75',
    function: '#268BD2',
    variable: '#B58900',
    operator: '#859900',
    type: '#CB4B16',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// Light Theme - GitHub Light
export const githubLight: Theme = {
  name: 'github-light',
  displayName: 'GitHub Light',
  description: 'GitHub official light theme',
  author: 'GitHub',
  type: 'light',
  colors: {
    primary: '#0969DA',
    secondary: '#CF222E',
    accent: '#1A7F37',
    bg: '#FFFFFF',
    bgAlt: '#F6F8FA',
    bgHighlight: '#F3F4F6',
    bgSelected: '#DDFBE6',
    text: '#24292F',
    textMuted: '#57606A',
    textHighlight: '#000000',
    textInverse: '#FFFFFF',
    success: '#1A7F37',
    warning: '#9A6700',
    error: '#CF222E',
    info: '#0969DA',
    border: '#D0D7DE',
    borderFocus: '#0969DA',
    borderMuted: '#E1E4E8',
    keyword: '#CF222E',
    string: '#0A3069',
    number: '#0550AE',
    comment: '#6E7781',
    function: '#8250DF',
    variable: '#953800',
    operator: '#CF222E',
    type: '#1A7F37',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// High Contrast Theme
export const highContrast: Theme = {
  name: 'high-contrast',
  displayName: 'High Contrast',
  description: 'High contrast theme for accessibility',
  author: 'SuperCode',
  type: 'dark',
  colors: {
    primary: '#00FFFF',
    secondary: '#FF00FF',
    accent: '#FFFF00',
    bg: '#000000',
    bgAlt: '#0A0A0A',
    bgHighlight: '#1A1A1A',
    bgSelected: '#003366',
    text: '#FFFFFF',
    textMuted: '#CCCCCC',
    textHighlight: '#FFFFFF',
    textInverse: '#000000',
    success: '#00FF00',
    warning: '#FFFF00',
    error: '#FF0000',
    info: '#00FFFF',
    border: '#FFFFFF',
    borderFocus: '#00FFFF',
    borderMuted: '#666666',
    keyword: '#FF00FF',
    string: '#00FF00',
    number: '#FFFF00',
    comment: '#808080',
    function: '#00FFFF',
    variable: '#FFFFFF',
    operator: '#FF00FF',
    type: '#00FF00',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// TOON Theme - Fun and colorful
export const toon: Theme = {
  name: 'toon',
  displayName: 'TOON',
  description: 'Fun, colorful cartoon-style theme',
  author: 'SuperCode',
  type: 'dark',
  colors: {
    primary: '#FF6B6B',
    secondary: '#4ECDC4',
    accent: '#FFE66D',
    bg: '#2C3E50',
    bgAlt: '#34495E',
    bgHighlight: '#3D566E',
    bgSelected: '#4A6785',
    text: '#ECF0F1',
    textMuted: '#95A5A6',
    textHighlight: '#FFFFFF',
    textInverse: '#2C3E50',
    success: '#2ECC71',
    warning: '#F39C12',
    error: '#E74C3C',
    info: '#3498DB',
    border: '#4A6785',
    borderFocus: '#FF6B6B',
    borderMuted: '#3D566E',
    keyword: '#E74C3C',
    string: '#2ECC71',
    number: '#9B59B6',
    comment: '#7F8C8D',
    function: '#3498DB',
    variable: '#F39C12',
    operator: '#E74C3C',
    type: '#1ABC9C',
  },
  icons: {
    folder: '🗂️',
    file: '📝',
    agent: '🦾',
    model: '🎯',
    tool: '🛠️',
    function: '💫',
    memory: '🧩',
    workflow: '🎪',
    chat: '🗨️',
    settings: '🎛️',
    success: '🎉',
    error: '💥',
    warning: '🔔',
    info: '💡',
    running: '🟢',
    stopped: '🔴',
    loading: '🔄',
  },
};

// Cyberpunk Theme
export const cyberpunk: Theme = {
  name: 'cyberpunk',
  displayName: 'Cyberpunk 2077',
  description: 'Neon-lit cyberpunk aesthetic',
  author: 'SuperCode',
  type: 'dark',
  colors: {
    primary: '#00F0FF',
    secondary: '#FF003C',
    accent: '#FFD700',
    bg: '#0D0221',
    bgAlt: '#150734',
    bgHighlight: '#1E0A47',
    bgSelected: '#2A0F5A',
    text: '#E0E0E0',
    textMuted: '#8A8A8A',
    textHighlight: '#FFFFFF',
    textInverse: '#0D0221',
    success: '#00FF9F',
    warning: '#FFD700',
    error: '#FF003C',
    info: '#00F0FF',
    border: '#2A0F5A',
    borderFocus: '#00F0FF',
    borderMuted: '#1E0A47',
    keyword: '#FF003C',
    string: '#00FF9F',
    number: '#FFD700',
    comment: '#5A5A5A',
    function: '#00F0FF',
    variable: '#FF9F00',
    operator: '#FF003C',
    type: '#00FF9F',
  },
  icons: {
    folder: '📁',
    file: '📄',
    agent: '🤖',
    model: '🧠',
    tool: '🔧',
    function: '⚡',
    memory: '💾',
    workflow: '🔄',
    chat: '💬',
    settings: '⚙️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    running: '●',
    stopped: '○',
    loading: '◐',
  },
};

// All themes collection
export const themes: Record<string, Theme> = {
  'vscode-dark': vscodeDark,
  'dracula': dracula,
  'one-dark-pro': oneDarkPro,
  'nord': nord,
  'monokai-pro': monokaiPro,
  'github-dark': githubDark,
  'github-light': githubLight,
  'catppuccin-mocha': catppuccinMocha,
  'tokyo-night': tokyoNight,
  'gruvbox-dark': gruvboxDark,
  'solarized-dark': solarizedDark,
  'high-contrast': highContrast,
  'toon': toon,
  'cyberpunk': cyberpunk,
};

export const defaultTheme = 'tokyo-night';

export function getTheme(name: string): Theme {
  return themes[name] || themes[defaultTheme];
}

export function listThemes(): Array<{ name: string; displayName: string; type: string }> {
  return Object.values(themes).map(t => ({
    name: t.name,
    displayName: t.displayName,
    type: t.type,
  }));
}
